docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "collection-2021-2.0"
python_version: "3.7"
pkg_name: ""
pkg_version: ""
extra_packages: "collection=2021C2.0=*_0"
channels: "-c nsls2forge -c defaults"
extra_cmd_before_install: "sudo yum install mesa-libGL -y"
extra_cmd_after_install: "conda remove perl --force -y"
docker_upload:
  - ghcr
  - dockerhub
  - quay
zenodo_upload: "no"
zenodo_metadata:
  metadata:
    title: "NSLS-II collection conda environment"
    upload_type: "software"
    description: "NSLS-II collection environment deployed to the experimental floor."
    creators:
      - name: Gedell, John
        affiliation: "St. Joseph's College"
      - name: Rakitin, Maksim
        affiliation: "Brookhaven National Laboratory"
