docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "lsdc-gui-2022-1.0"
conda_binary: "mamba"
python_version: "3.6"
pkg_name: ""
pkg_version: ""
extra_packages: "pyolog pymca qtpy pyqt pyepics PyYAML pillow opencv jsonschema conftrak analysisstore amostra==0.2 ispyb==5.6.2 python-confluent-kafka matplotlib ophyd mysql-connector-python==8.0.18 qt_epics"
channels: "-c conda-forge"
