docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "lsdc-gui-1.0"
python_version: "3.6"
pkg_name: ""
pkg_version: ""
extra_packages: "pyolog pymca qtpy pyqt pyepics PyYAML pillow opencv jsonschema conftrak abbix_analysisstore amostra==0.2 ispyb==5.6.2 python-confluent-kafka"
channels: "-c conda-forge -c lightsource2-tag"
