docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
conda_binary: "mamba"
env_name: "lsdc-server_2021-1.3"
python_version: "3.7"
pkg_name: ""
pkg_version: ""
extra_packages: "collection jsonschema conftrak abbix_analysisstore amostra==0.2 ispyb==5.6.2 python-confluent-kafka mamba bluesky-live"
extra_cmd_after_install: "conda activate /opt/conda_envs/lsdc-server_2021-1.3 && python -m pip install git+https://github.com/NSLS-II-nyx/nyxtools.git && conda deactivate && conda list"
channels: "-c conda-forge -c lightsource2-tag"
