docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
conda_binary: "mamba"
env_name: "lsdc-server"
python_version: "3.7"
pkg_name: ""
pkg_version: "2021-1.5"
extra_packages: "ipython collection jsonschema conftrak analysisstore amostra==0.2 ispyb==5.6.2 python-confluent-kafka mamba bluesky-live xlrd nyxtools"
extra_cmd_after_install: ""
channels: "-c conda-forge"
