docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "mx-scripts"
python_version: "3.9"
pkg_name: ""
pkg_version: "2022-1.0"
extra_packages: "python-confluent-kafka pyepics yaml"
channels: "-c conda-forge"
