docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "n2sn"
python_version: "3.9.4"
pkg_name: "n2snusertools"
pkg_version: "0.3.6"
extra_packages: ""
channels: "-c nsls2forge -c defaults"
docker_upload: "ghcr"
zenodo_metadata:
    metadata:
        title: "SULI Summer"
        upload_type: "software"
        description: "This is a SULI summer intern project."
        creators:
          -
            name: Gedell, John
            affiliation: "St. Joseph's College"
          -
            name: Rakitin, Maksim
            affiliation: "Brookhaven National Lab"
