docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "n2sn"
python_version: "3.9"
pkg_name: "n2snusertools"
pkg_version: &version "0.3.6"
extra_packages: "krb5 python-gssapi"
channels: "-c conda-forge"
docker_upload:
  - ghcr
  - dockerhub
  - quay
zenodo_metadata:
  metadata:
    title: "User tools for the NSLS-II Science Network"
    upload_type: "software"
    description: "User tools for the NSLS-II Science Network. https://github.com/NSLS-II/N2SNUserTools"
    version: *version
    creators:
      - name: Gedell, John
        affiliation: "St. Joseph's College"
      - name: Rakitin, Maksim
        affiliation: "Brookhaven National Laboratory"
