docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "n2sn"
python_version: "3.9.4"
pkg_name: "n2snusertools"
pkg_version: "0.3.6"
extra_packages: ""
channels: "-c nsls2forge -c defaults"
docker_upload: "ghcr;dockerhub;quay"
zenodo_metadata:
  metadata:
    title: "User tools for the NSLS-II Science Network"
    upload_type: "software"
    description: "User tools for the NSLS-II Science Network. https://github.com/NSLS-II/N2SNUserTools"
    version: "0.3.6"
    creators:
      - name: Gedell, John
        affiliation: "St. Joseph's College"
      - name: Rakitin, Maksim
        affiliation: "Brookhaven National Laboratory"
