docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_name: "nsls2-analysis-2021-2.0"
python_version: "3.7"
pkg_name: ""
pkg_version: ""
extra_packages: "nsls2-analysis=2021C2.0=*_1"
channels: "-c nsls2forge -c defaults"
extra_cmd_before_install: "sudo yum install mesa-libGL -y"
extra_cmd_after_install: "conda remove perl --force -y"
