docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "nsls2-collection-2021-2.0"
python_version: "3.7"
pkg_name: ""
pkg_version: ""
extra_packages: "nsls2-collection=2021C2.0=*_0"
channels: "-c conda-forge"
extra_cmd_before_install: "sudo yum install mesa-libGL mesa-libGL-devel -y"
extra_cmd_after_install: "conda remove perl --force -y"
