docker_image: "quay.io/condaforge/linux-anvil-comp7:latest"
env_name: "tomviz-{{ today }}"
conda_binary: "mamba"
python_version: "3.7"
pkg_name: "tomviz"
pkg_version: "1.10.0.post94"
extra_packages: "databroker area-detector-handlers tomopy pyxrf"
channels: "-c conda-forge"
