metadata:
  title: "SULI Summer"
  upload_type: "software"
  description: "This is a SULI summer intern project."
  creators:
    -
      name: Gedell, John
      affiliation: "St. Joseph's College"
    -
      name: Rakitin, Maksim
      affiliation: "Brookhaven National Lab"
