name : tests

on:
  push:
  pull_request:

jobs:
  generate_conda_packd_envs:
    name: Generate conda-pack'd envs with ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
      fail-fast: false

    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "conda-pack"
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: pip-install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: pip-install dev-dependencies
        run: python3 -m pip install -r requirements-dev.txt

      - name: render n2sn config
        shell: bash -l {0}
        run: |
          # For reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.
          set -vxeuo pipefail
          python3 render.py -c configs/n2sn.yml
          ls -la
          cat ./Dockerfile
          cat ./runner-n2sn.sh

      - name: run a build with Docker
        shell: bash -l {0}
        run: |
          # For reference: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.
          set -vxeuo pipefail
          bash ./runner-n2sn.sh
          ls -la
